apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      containers:
      - name: vulnerable-container
        image: nginx:latest
        securityContext:
          privileged: true # Vulnerable
          runAsUser: 0     # Vulnerable
        ports:
        - containerPort: 80
